### ISSUE TITLE
Repeated invocation of gherkinfmt on the same file increasingly adds blank lines between scenarios

### ISSUE THREAD

**Issue by dnwe** [muhqu/go-gherkin#17]
If you repeatedly run gherkinfmt on a `.feature` file, it will repeatedly add newlines between Scenarios. It *seems* to be related to the handling/preservation of blanklines between steps (mentioned in #3)

[formater.go#L303-L305](https://github.com/muhqu/go-gherkin/blob/d760e1a4a87a71c107f186719fdc57db0e1d27ea/formater/formater.go#L303-L305)

Unfortunately the go Examples library doesn't lend itself well to adding a unittest to cover trailing whitespace.

Ideally you could re-run gherkinfmt on a previously formatted .feature file and it would essentially be a no-op. If that also didn't introduce any trailing whitespace that would be an added bonus :)

**Comment by muhqu** [comment]
@dnwe the issue should be fixed now… just pushed a new release of `gherkinfmt`: https://github.com/muhqu/gherkinfmt/releases/tag/v1.0.2
